### ISSUE TITLE
Capture other address lines besides address_line_1

### ISSUE THREAD

**Issue by konklone** [18F/foia-hub#127]
It's a little incomplete. Right now, this:

``` yaml
abbreviation: GSA
departments:
- address:
  - FOIA Contact
  - FOIA Requester Service Center (H1C)
  - Room 7308
  - 1800 F. Street, NW
  - Washington, DC 20405
```

We only read in the last 3 lines of the address. I think we want something like an `address_lines` field, with an array in it, that we can iterate over (while still putting the last couple lines into their own `street`, `state`, `city`, and `zip` fields as they are now).
