### ISSUE TITLE
YAML field names for statistics have spaces and dashes in them

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#244]
In our contact data YAML files we've been using underscores to separate words. The new statistics stuff has field names with spaces and dashes. Let's try and see if we have those field names be consistent. 

Instead of this: 

``` yaml
      Complex-Average No. of Days: '285'
      Complex-Highest No. of Days: '1010'
      Complex-Lowest No. of Days: '2'
      Complex-Median No. of Days: '258'
      Expedited Processing-Average No. of Days: '36'
      Expedited Processing-Highest No. of Days: '42'
      Expedited Processing-Lowest No. of Days: '30'
      Expedited Processing-Median No. of Days: '36'
      Simple-Average No. of Days: '127'
      Simple-Highest No. of Days: '714'
      Simple-Lowest No. of Days: '1'
      Simple-Median No. of Days: '59'
```

I could see something like this: 

``` yaml
      complex_average_days: '285'
      complex_highest_days: '1010'
      complex_lowest_days: '2'
      complex_median_days: '258'
      expedited_processing_average_days: '36'
      expedited_processing_highest_days: '42'
      expedited_processing_lowest_days: '30'
      expedited_processing_median_days: '36'
      simple_average_days: '127'
      simple_highest_days: '714'
      simple_lowest_days: '1'
      simple_median_days: '59'
```
