### ISSUE TITLE
Reformat address field 

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#390]
Reformat yaml address field to be more explicit so we don't have to wrangle any data on the loading function. 

I.E.
```yaml
- address:
  - Denise Garrett
  - Supervisory Copyright Information Specialist, GC/I&R
  - P.O. Box 70400, SW
  - Washington, DC 20024 
```
to 
```yaml
- address:
   name: Denise Garrett
   title: Supervisory Copyright Information Specialist, GC/I&R
   address: P.O. Box 70400, SW
   city: Washington 
   state: DC 
   zip: 20024 
```

**Comment by ramirezg** [comment]
Maybe let's wait on this until #387. We might want to reformat to allow for multiple addresses.

**Comment by khandelwal** [comment]
#387 is closed. How does that relate to this issue?

**Comment by ramirezg** [comment]
@khandelwal if we had used the csv for the data as #387 proposed then we wouldn't have needed to update the scraper

**Comment by ramirezg** [comment]
18F/foia/pull/97 should solve this. The final iteration isn't ideal, but the data was a little messy. The final format is more like this:

```yaml
- address:
   address_lines: 
     - Denise Garrett
     - Supervisory Copyright Information Specialist, GC/I&R
   address: P.O. Box 70400, SW
   city: Washington 
   state: DC 
   zip: 20024 
```
