### ISSUE TITLE
Reformat public_liaison/foia_officer/misc field in yamls

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#394]
Update the contacts to be more explicit in yaml files so we don't have to do any data munging in the loading function. 

`public_liaison: 'Denise Garrett, Phone: (202) 707-6800'` and `foia_officer: FirstName LastName, Phone: xxx-xxx-xxxx` might be better as
```yaml
contacts:
  public_liaison: 
    name: Denise Garrett 
    phone: 
       - 202-707-6800
  foia_officer:
    name: FirstName LastName
    phone: 
       - xxx-xxx-xxxx
```
