### ISSUE TITLE
How do we store metadata associated with documents?

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#493]
When we import the documents, we'll need to store the metadata with the documents somehow. In the search prototype each directory had a YAML manifest file that contained information about the documents. 

Is there a better way to do this? 

```yaml
- document:
    document_id: C17528290.pdf
    title: "THIRD CONFERENCE OF THE PARTIES TO THE CLIMATE CONVENTION, UPDATE NO 6: REPORT ON ACTIVITIES/MEETINGS ON DECEMBER 4/5, 1997"
    document_date: 19971205
- document:
    document_id: C17577793.pdf
    title: "COUNTRY REPORTS ON HUMAN RIGHTS PRACTICES INSTRUCTIONS FOR PREPARATION AND DRAFTING OF THE ANNUAL REPORT"
    document_date: 20010701
- document:
    document_id: C17641032.pdf
    title: "PUBLIC ANNOUNCEMENT - WORLDWIDE CAUTION"
    document_date: 20010530
```
